-- QUERIES DO EXERCICIO 03

-- RELATORIO GERAL DE TODOS OS CLIENTES
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;


-- RELATORIO DE HOMENS
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE C.SEXO = 'M';


-- RELATORIO DE MULHERES
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE C.SEXO = 'F'; 


-- QUANTIDADE DE HOMENS E MULHERES
SELECT SEXO, COUNT(*)
  FROM CLIENTE 
 GROUP BY SEXO;


-- IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NAO TENHAM CELULAR
SELECT C.IDCLIENTE, C.NOME, C.EMAIL, E.BAIRRO, E.CIDADE, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE E.BAIRRO LIKE '%CENTRO%'
   AND E.CIDADE = 'RIO DE JANEIRO'
   AND T.NUMERO = NULL;


-- MUDANDO OS CADASTROS COM O SEXO CADASTRADO ERRADO
UPDATE CLIENTE SET SEXO = 'F'
 WHERE IDCLIENTE IN (9, 10, 11, 15);


UPDATE CLIENTE SET SEXO = 'M'
 WHERE IDCLIENTE = '13'; 



/* PARA UM CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL, E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE T.TIPO = 'CEL'
   AND E.ESTADO = 'RJ'; 


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU 
UM RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR  
DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR*/

SELECT C.NOME, C.EMAIL, T.NUMERO
  FROM CLIENTE C
 INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE C.SEXO = 'F'
   AND T.TIPO = 'CEL'
   AND E.ESTADO = 'SP';


-- CRIACAO DA DATABASE E DAS TABELAS PARA O EXERCICIO 03
CREATE DATABASE COMERCIO;

USE COMERCIO;

-- CRIANDO TABELAS DO BANCO COMERCIO
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	EMAIL VARCHAR(100)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL UNIQUE,
	RUA VARCHAR(100),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO CHAR(2),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	TIPO CHAR(3), -- COM, FIX, CEL
	NUMERO VARCHAR(20) NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

-- INSERTS PARA O EXERCICIO
-- INSERT NA TABELA CLIENTE
INSERT INTO CLIENTE VALUES(NULL,'LUIS','M','159263479','LUIS@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL,'BRUNO','M','258963147','BRUNO@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','789654123','ANDRE@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL,'ROSANE','F','159789236','ROSANE@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F','2651456987','CLARA@GMAIL.COM');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

-- INSERTS NA TABELA ENDERECO
INSERT INTO ENDERECO VALUES(NULL, 2, 'RUA GRAVATAI', 'PRIMAVERA', 'DOIS IRMAOS', 'RS');
INSERT INTO ENDERECO VALUES(NULL, 1, 'RUA ESTEIO', 'FLORESTA', 'DOIS IRMAOS', 'RS');
INSERT INTO ENDERECO VALUES(NULL, 3, 'RUA SAO LEOPOLDO', 'PRIMAVERA', 'DOIS IRMAOS', 'RS');
INSERT INTO ENDERECO VALUES(NULL, 4, 'AV SAO MIGUEL', 'CENTRO', 'DOIS IRMAOS', 'RS');
INSERT INTO ENDERECO VALUES(NULL, 5, 'AV DEZ DE SETEMBRO', 'CENTRO', 'DOIS IRMAOS', 'RS');
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',6);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',7);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',9);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',10);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',12);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',13);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',14);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',15);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',16);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',17);
INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',18);

-- INSERTS NA TABELA TELEFONE
INSERT INTO TELEFONE VALUES(NULL, 1, 'CEL', '912657832');
INSERT INTO TELEFONE VALUES(NULL, 1, 'FIX', '35644202');
INSERT INTO TELEFONE VALUES(NULL, 3, 'CEL', '995623287');
INSERT INTO TELEFONE VALUES(NULL, 2, 'CEL', '954218765');
INSERT INTO TELEFONE VALUES(NULL, 3, 'CEL', '932653291');
INSERT INTO TELEFONE VALUES(NULL, 1, 'CEL', '995516284');
INSERT INTO TELEFONE VALUES(NULL, 4, 'CEL', '932235654');
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'RES','68976565',6);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'CEL','99656675',7);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'CEL','33567765',8);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'CEL','88668786',9);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'COM','55689654',10);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'COM','88687979',11);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'COM','88965676',11);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'CEL','89966809',12);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'COM','88679978',13);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'CEL','99655768',13);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'RES','89955665',15);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'RES','77455786',17);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'RES','89766554',17);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'RES','77755785',15);
INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL,'COM','44522578',6);